Fixes when MultiSortingComparison is called with unnamed extractors
Note there is still a bug:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-63-f467686fd709> in <module>
----> 1 comparison_dm_ks = st.comparison.MultiSortingComparison((decaymodel_se, hs_filtered_se))

/disk/scratch/mhennig/spikeinterface/spiketoolkit/spiketoolkit/comparison/multisortingcomparison.py in __init__(self, sorting_list, name_list, delta_tp, minimum_accuracy)
     16         self._delta_tp = delta_tp
          17         self._min_accuracy = minimum_accuracy
	  ---> 18         self._do_matching()
	       19
	            20     def get_sorting_list(self):

/disk/scratch/mhennig/spikeinterface/spiketoolkit/spiketoolkit/comparison/multisortingcomparison.py in _do_matching(self)
     83                                             'avg_agreement': avg_agr,
          84                                             'sorter_unit_ids': sorting_idxs}
	  ---> 85                 self._spiketrains.append(self._sorting_list[self._name_list.index(sorter)].get_unit_spike_train(unit))
	       86                 unit_id += 1
	            87                 # print("ADDING NODE (no match): ", n)

ValueError: sequence.index(x): x not in sequence
```